[package]
org = "kajendran"
name = "int_api"
version = "0.1.0"
title = "int-api"

[build-options]
sticky = true

[[tool.openapi]]
id = "getusers1"
targetModule = "getusers1"
filePath = "./.choreo/getusers1-spec.yaml"

[[tool.openapi]]
id = "enrichusersv2"
targetModule = "enrichusersv2"
filePath = "./.choreo/enrichusersv2-spec.yaml"
