[package]
org = "kajendran"
name = "demo_automation"
version = "0.1.0"
title = "demo-automation"

[build-options]
sticky = true

[[tool.openapi]]
id = "getusers"
targetModule = "getusers"
filePath = "./.choreo/getusers-spec.yaml"

[[tool.openapi]]
id = "enrichusers"
targetModule = "enrichusers"
filePath = "./enrichusers_openapi.yaml"
